title: LaM-SLidE
description: "LaM-SLidE - {La}tent Space {M}odeling of Spatial Dynamical {S}ystems via {Li}nke{d} {E}ntities"
show_downloads: false
theme: jekyll-theme-cayman
kramdown:
  math_engine: mathjax
